config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts

      root to: "users#index"
    end
  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/views/shared/_flashes.html.erb
<div>
  <% if notice %>
    <div class="alert alert-success alert-dismissible"  role="alert">
      <div> <%= notice %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible"  role="alert">
      <div> <%= alert %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<div class='logo'>
	<h1>Time Tracker</h1>
</div>

<% if current_user %>
  <nav class="custom-nav navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link #{active?(root_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Time Entries", posts_path, class: "nav-link #{active?(posts_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add New Entry", new_post_path, id: "new_post_from_nav", class: "nav-link #{active?(new_post_path)}" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user.type == 'AdminUser' %>
                <li>
                  <%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-item"  %>
                </li>
                <li><hr class="dropdown-divider"></li>
              <% end %>
              <li>
                <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>