config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts

      root to: "users#index"
    end
  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/post.rb
class Post < ApplicationRecord
    enum status: { submitted: 0, approved: 1, rejected: 2 }
    belongs_to :user
    validates_presence_of :date, :rationale, :overtime_request

    validates :overtime_request, numericality: { greater_than: 0.0 }

    scope :post_by, ->(user) { where(user_id: user.id) }
  end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.post_by current_user
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id

        # debugger
        if @post.save
            redirect_to @post, notice: 'Your post was created successfully'
        else
            render :new
        end
    end

    def edit
        authorize @post
    end

    def show
    end

    def destroy
        @post.delete
        redirect_to posts_path, notice: 'Your post was deleted successfully'
    end

    def update
        authorize @post

        if @post.update(post_params)
            redirect_to @post, notice: 'Your post was edited successfully'
        else
            render :edit
        end
    end

    private

    def post_params
        params.require(:post).permit(:date, :rationale, :status, :overtime_request)
    end

    def set_post
        @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def status_label status
    status_span_generator status
  end

  private

  def status_span_generator status
    case status
    when 'submitted'
      content_tag(:span, status.titleize, class: 'badge bg-primary')
    when 'approved'
      content_tag(:span, status.titleize, class: 'badge bg-success')
    when 'rejected'
      content_tag(:span, status.titleize, class: 'badge bg-danger')
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

  <% if @post.errors.any? #kmm TODO not working  %>
    <% @post.errors.full_messages.each do |error| %>
        <%= @post.errors.inspect %>
    <% end %>
  <% end %>

  <div class="form-group">
      <%= f.label :overtime_request, class: 'col-sm-2 control-label' %>
      <%= f.text_field :overtime_request, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :date, class: 'col-sm-2 control-label' %>
      <%= f.date_field :date, class: "form-control" %>
  </div>
  
  <div class="form-group">
      <%= f.label :rationale, class: 'col-sm-2 control-label' %>
      <%= f.text_area :rationale, class: "form-control" %>
  </div>

  <%= render partial: 'status', locals: {f: f} if current_user.type == 'AdminUser' %>
  
  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
<% end %> 

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.id %>
  </td>
  <td>
    <%= post.overtime_request %>
  </td>
  <td>
    <%= post.date %>
  </td>
  <td>
    <%= post.user.full_name %>
  </td>
  <td>
    <%= link_to truncate(post.rationale), post %>
  </td>
  <td>
    <%= status_label post.status %>
  </td>
  <td>
    <%= link_to '', edit_post_path(post), id: "edit_#{post.id}", class: 'bi bi-pencil index-icons' if policy(post).update? %>
  </td>
  <td>
    <%= link_to '', post_path(post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, id: "delete_post_#{post.id}_from_index", class: 'bi bi-trash index-icons' %>
  </td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
    <%= f.radio_button :status, 'submitted' %>
    <%= f.label :status, 'Submitted' %>

    <%= f.radio_button :status, 'approved' %>
    <%= f.label :status, 'Approved' %>

    <%= f.radio_button :status, 'rejected' %>
    <%= f.label :status, 'Rejected' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= render 'form'  %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Overtime Requested
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
			<th>
				Status
			</th>
		</tr>
	</thead>
	<tbody>
		<%= render @posts %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
    <%= f.date_field :date %>
    <%= f.text_area :rationale %>

    <%= f.submit "Save" %>
<% end %>

app/views/posts/show.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h2 class="card-title"><%= @post.rationale %></h2>

    <div class="mb-2">
      <h3 class="h5"><span>Overtime Amount Requested:</span> <%= @post.overtime_request %></h3>
    </div>

    <div class="mb-2">
      <h3 class="h5"><span>Employee:</span> <%= @post.user.full_name %></h3>
    </div>

    <div class="mb-2">
      <h3 class="h5"><span>Date:</span> <%= @post.date %></h3>
    </div>

    <div class="mb-2">
      <h3 class="h5"><span>Current Stage of Approval:</span> <%= @post.status %></h3>
    </div>
  </div>
</div>